title: jQuery countdown timer control
description: jQuery countdown timer plugin with optional control button, based on the https://github.com/caike/jQuery-Simple-Timer
show_downloads: true
google_analytics: UA-143061855-1
theme: jekyll-theme-minimal
